version: '3.8'
services:
  backend:
    # build: ./docker
    image: node:latest
    # image: nestjs/cli:latest
    ports:
    - 3000:3000
    volumes:
    - ./:/app
    # working_dir: /app/music-store
    working_dir: /app
    command: ./node_modules/.bin/nest start --watch --debug
    # command: nest start --watch --debug
    env_file: .env
    depends_on:
    - mq
  mq:
    image: bitnami/redis:latest
    ports:
    - 6379:6379
    environment:
    - REDIS_REPLICATION_MODE=master
    - ALLOW_EMPTY_PASSWORD=yes
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   ports:
  #   - 50000:50000
  #   - 8080:8080
